name: APP dev
on:
  push:
    branches: [ main ]
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  setVariable:
    runs-on: ubuntu-latest

    outputs:
      id: setVar
      outputs: 
        newString: ${{ steps.setVar.outputs.newString }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set variable without spaces
      id: setVar
      run: |
        originalString="This is a sample string with spaces"
        newString=$(echo $originalString | tr ' ' '-')
        echo "::set-output name=newString::$newString"

    - name: Use the variable
      run: echo "Variable Without Spaces:${{ needs.setVar.outputs.newString }}"
