name: APP dev
on:
  push:
    branches: [ main ]
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  setVariable:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set variable without spaces
      id: setVar
      run: |
        originalString="This is a sample string with spaces"
        newString=$(echo "${{ github.event.head_commit.message }}" | tr ' ' '-')
        echo $newString
        echo "commitmessage=$newString" >> $GITHUB_ENV
    - name: Use the variable
      run: echo "Variable Without Spaces:${{ env.commitmessage }}"
