name: APP dev
on:
  push:
    branches: [ main ]
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  test:  
    runs-on: windows-2022
    
    name: Test solution   
    steps:
    - name: Checkout
      run: |
        echo "Finished main of net6"
  create_pull_request:
    runs-on: windows-2022
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Pull Request
        run: |
          git checkout -b net6
          git push main net6
          gh pr create --base net6 --head main --title "PR_TITLE=Automated pull request from ${{ github.event_name }} branch: ${{ github.ref_name }}" --body "Automated pull request from main to net6"
  
    
