name: APP dev
on:
  push:
    branches: [ main ]    
jobs:
  test:  
    runs-on: windows-2022
    
    name: Test solution   
    steps:
    - name: Checkout
      run: |
        echo "Finished main of net6"
  create_pull_request:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          ref: net6
      - name: Reset net6 branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: net6-promotion
  
    
