name: APP dev
on:
  push:
    branches: [ main ]
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  setVariable:
    runs-on: ubuntu-latest

    outputs:
        newString: ${{ steps.setVar.outputs.commitmessage }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set variable without spaces
      id: setVar
      run: |
        originalString="This is a sample string with spaces"
        newString=$(echo $originalString | tr ' ' '-')
        echo "commitmessage=$newString" >> $env:GITHUB_OUTPUT

    - name: Use the variable
      run: echo "Variable Without Spaces:${{ steps.setVar.outputs.commitmessage }}"
